services:
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - api

  api:
    build: ./backend
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/imagehost?sslmode=disable"
      STORAGE_PATH: "./uploads"
      BASE_URL: "your_ip_here:port"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imagehost
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: